FROM ubuntu:latest

RUN apt-get update && apt-get install -y tzdata
RUN rm /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && date
RUN apt-get install -y git curl pkg-config libx11-dev libxkbfile-dev libsecret-1-dev

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install -y nodejs && apt-get clean
RUN npm install -g yarn && npm cache clean --force

ENTRYPOINT [ "sh", "node" ]